/*==========================================================*
 * BeyBuilder v1.5 for Beyblade X                           *
 * Author: Fabel                                            *
 * Copyright 2023-2026                                      *
 *==========================================================*/

//0 weight means no weight data yet, same for height

var bitChips = [ 

    {"name":"Dran",     "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Dr", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Wizard",   "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Wz", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Perseus",  "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Pr", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"Hells",    "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Hl", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"Rhino",    "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Rh", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Fox",      "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Fx", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Pegasus",  "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Pg", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Cerberus", "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Cr", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Whale",    "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Wh", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"Valkyrie", "spin":"right", "system":"CX", "type":"metal",       "weight":5.43, "height":0, "abbv":"Vl", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Hornet",   "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Hr", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Kraken",   "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Kr", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Stag",     "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"St", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Sol",      "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Sl", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Wolf",     "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Wl", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Emperor",  "spin":"right", "system":"CX", "type":"metal-light", "weight":4.73, "height":0, "abbv":"Em", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Leon",     "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Ln", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Phoenix",  "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Ph", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"Bahamut",  "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Bh", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"Knight",   "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Kn", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Ragna",    "spin":"right", "system":"CX", "type":"standard",    "weight":1.73, "height":0, "abbv":"Rn", "wins":0, "losses":0, "draws":0, "id":20},

];

var overBlades = [

    {"name":"Break",     "spin":"right", "system":"CX2", "type":"standard",    "weight":0, "height":0, "abbv":"B", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Guard",     "spin":"right", "system":"CX2", "type":"standard",    "weight":0, "height":0, "abbv":"G", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Flow",      "spin":"right", "system":"CX2", "type":"standard",    "weight":0, "height":0, "abbv":"F", "wins":0, "losses":0, "draws":0, "id":2},

]

var blades = [
  
    {"name":"CobaltDrake",       "spin":"right", "system":"BX",  "weight":36.80, "height":0, "abbv":"CbDr", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"DranSword",         "spin":"right", "system":"BX",  "weight":34.97, "height":0, "abbv":"DrSw", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"HellsScythe",       "spin":"right", "system":"BX",  "weight":32.94, "height":0, "abbv":"HlSc", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"KnightShield",      "spin":"right", "system":"BX",  "weight":32.70, "height":0, "abbv":"KnSh", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"WizardArrow",       "spin":"right", "system":"BX",  "weight":31.86, "height":0, "abbv":"WzAr", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"DranzerSpiral",     "spin":"right", "system":"BX",  "weight":27.82, "height":0, "abbv":"DrSp", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"KnightLance",       "spin":"right", "system":"BX",  "weight":33.25, "height":0, "abbv":"KnLn", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"SharkEdge",         "spin":"right", "system":"BX",  "weight":34.60, "height":0, "abbv":"ShEd", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"LeonClaw",          "spin":"right", "system":"BX",  "weight":31.40, "height":0, "abbv":"LnCl", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"ViperTail",         "spin":"right", "system":"BX",  "weight":34.55, "height":0, "abbv":"VpTl", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"DranDagger",        "spin":"right", "system":"BX",  "weight":34.91, "height":0, "abbv":"DrDg", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"HellsChain",        "spin":"right", "system":"BX",  "weight":33.33, "height":0, "abbv":"HlCh", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"RhinoHorn",         "spin":"right", "system":"BX",  "weight":32.82, "height":0, "abbv":"RhHr", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"PhoenixFeather",    "spin":"right", "system":"BX",  "weight":33.33, "height":0, "abbv":"PhFt", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"PhoenixWing",       "spin":"right", "system":"BX",  "weight":38.00, "height":0, "abbv":"PhWn", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"WyvernGale",        "spin":"right", "system":"BX",  "weight":32.10, "height":0, "abbv":"WvGl", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"UnicornSting",      "spin":"right", "system":"BX",  "weight":33.38, "height":0, "abbv":"UnSt", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"SphinxCowl",        "spin":"right", "system":"BX",  "weight":32.80, "height":0, "abbv":"SpCw", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"DranBuster",        "spin":"right", "system":"UX",  "weight":36.32, "height":0, "abbv":"DrBs", "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"HellsHammer",       "spin":"right", "system":"UX",  "weight":33.20, "height":0, "abbv":"HlHm", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"WizardRod",         "spin":"right", "system":"UX",  "weight":35.35, "height":0, "abbv":"WzRd", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"DrigerSlash",       "spin":"right", "system":"BX",  "weight":28.50, "height":0, "abbv":"DrSl", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"TyrannoBeat",       "spin":"right", "system":"BX",  "weight":36.90, "height":0, "abbv":"TrBt", "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"ShinobiShadow",     "spin":"right", "system":"UX",  "weight":28.23, "height":0, "abbv":"ShSh", "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"MammothTusk",       "spin":"right", "system":"BX",  "weight":32.10, "height":0, "abbv":"MmTs", "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"ShinobiKnife",      "spin":"right", "system":"BX",  "weight":30.90, "height":0, "abbv":"ShKf", "wins":0, "losses":0, "draws":0, "id":25},
    {"name":"PteraSwing",        "spin":"right", "system":"BX",  "weight":34.25, "height":0, "abbv":"PtSw", "wins":0, "losses":0, "draws":0, "id":26},
    {"name":"SamuraiSteel",      "spin":"right", "system":"BX",  "weight":31.08, "height":0, "abbv":"StSa", "wins":0, "losses":0, "draws":0, "id":27},
    {"name":"WeissTiger",        "spin":"right", "system":"BX",  "weight":34.83, "height":0, "abbv":"WsTg", "wins":0, "losses":0, "draws":0, "id":28},
    {"name":"CobaltDragoon",     "spin":"left",  "system":"BX",  "weight":37.80, "height":0, "abbv":"CbDg", "wins":0, "losses":0, "draws":0, "id":29},
    {"name":"BlackShell",        "spin":"right", "system":"BX",  "weight":32.43, "height":0, "abbv":"BlSh", "wins":0, "losses":0, "draws":0, "id":30},
    {"name":"Optimus Prime",     "spin":"right", "system":"BX",  "weight":31.75, "height":0, "abbv":"OpPr", "wins":0, "losses":0, "draws":0, "id":31},
    {"name":"Starscream",        "spin":"right", "system":"BX",  "weight":29.81, "height":0, "abbv":"St",   "wins":0, "losses":0, "draws":0, "id":32},
    {"name":"Optimus Primal",    "spin":"right", "system":"BX",  "weight":32.43, "height":0, "abbv":"OpPl", "wins":0, "losses":0, "draws":0, "id":33},
    {"name":"Megatron",          "spin":"right", "system":"BX",  "weight":31.50, "height":0, "abbv":"Mt",   "wins":0, "losses":0, "draws":0, "id":34},
    {"name":"AeroPegasus",       "spin":"right", "system":"UX",  "weight":38.00, "height":0, "abbv":"ArPg", "wins":0, "losses":0, "draws":0, "id":35},
    {"name":"LeonCrest",         "spin":"right", "system":"UX",  "weight":34.82, "height":0, "abbv":"LnCr", "wins":0, "losses":0, "draws":0, "id":36},
    {"name":"PhoenixRudder",     "spin":"right", "system":"UX",  "weight":34.68, "height":0, "abbv":"PhRd", "wins":0, "losses":0, "draws":0, "id":37},
    {"name":"CrocoCrunch",       "spin":"right", "system":"BX",  "weight":34.05, "height":0, "abbv":"CrCr", "wins":0, "losses":0, "draws":0, "id":38},
    {"name":"Yell Kong",         "spin":"right", "system":"BX",  "weight":31.24, "height":0, "abbv":"YlKn", "wins":0, "losses":0, "draws":0, "id":39},
    {"name":"Iron Man",          "spin":"right", "system":"BX",  "weight":32.07, "height":0, "abbv":"IrMn", "wins":0, "losses":0, "draws":0, "id":40},
    {"name":"Thanos",            "spin":"right", "system":"BX",  "weight":29.32, "height":0, "abbv":"Th",   "wins":0, "losses":0, "draws":0, "id":41},
    {"name":"Spider-man",        "spin":"right", "system":"BX",  "weight":33.06, "height":0, "abbv":"SpMn", "wins":0, "losses":0, "draws":0, "id":42},
    {"name":"Venom",             "spin":"right", "system":"BX",  "weight":34.56, "height":0, "abbv":"Vn",   "wins":0, "losses":0, "draws":0, "id":43},
    {"name":"Luke Skywalker",    "spin":"right", "system":"BX",  "weight":30.19, "height":0, "abbv":"LkSk", "wins":0, "losses":0, "draws":0, "id":44},
    {"name":"Darth Vader",       "spin":"right", "system":"BX",  "weight":30.40, "height":0, "abbv":"DrVd", "wins":0, "losses":0, "draws":0, "id":45},
    {"name":"Moff Gideon",       "spin":"right", "system":"BX",  "weight":30.59, "height":0, "abbv":"MgGd", "wins":0, "losses":0, "draws":0, "id":46},
    {"name":"The Mandalorian",   "spin":"right", "system":"BX",  "weight":30.88, "height":0, "abbv":"ThMn", "wins":0, "losses":0, "draws":0, "id":47},
    {"name":"WhaleWave",         "spin":"right", "system":"BX",  "weight":38.15, "height":0, "abbv":"WhWv", "wins":0, "losses":0, "draws":0, "id":48},
    {"name":"L-Drago:Upper",     "spin":"left",  "system":"BX",  "weight":33.85, "height":0, "abbv":"LLDU", "wins":0, "losses":0, "draws":0, "id":49},
    {"name":"L-Drago:Rapid Hit", "spin":"left",  "system":"BX",  "weight":33.22, "height":0, "abbv":"LLDR", "wins":0, "losses":0, "draws":0, "id":50},
    {"name":"BearScratch",       "spin":"right", "system":"BX",  "weight":29.74, "height":0, "abbv":"SvBr", "wins":0, "losses":0, "draws":0, "id":51},
    {"name":"Roar Tyranno",      "spin":"right", "system":"BX",  "weight":35.97, "height":0, "abbv":"RrTn", "wins":0, "losses":0, "draws":0, "id":52},
    {"name":"SilverWolf",        "spin":"right", "system":"UX",  "weight":36.83, "height":0, "abbv":"SlWl", "wins":0, "losses":0, "draws":0, "id":53},
    {"name":"CrimsonGaruda",     "spin":"right", "system":"BX",  "weight":34.90, "height":0, "abbv":"CrGr", "wins":0, "losses":0, "draws":0, "id":54},
    {"name":"SamuraiSaber",      "spin":"right", "system":"UX",  "weight":36.41, "height":0, "abbv":"Smba", "wins":0, "losses":0, "draws":0, "id":55},
    {"name":"KnightMail",        "spin":"right", "system":"UX",  "weight":36.61, "height":0, "abbv":"KnMl", "wins":0, "losses":0, "draws":0, "id":56},
    {"name":"DracielShield",     "spin":"right", "system":"BX",  "weight":28.15, "height":0, "abbv":"DcSh", "wins":0, "losses":0, "draws":0, "id":57},
    {"name":"ImpactDrake",       "spin":"right", "system":"UX",  "weight":38.85, "height":0, "abbv":"ImDr", "wins":0, "losses":0, "draws":0, "id":58},
    {"name":"GhostCircle",       "spin":"right", "system":"UX",  "weight":26.71, "height":0, "abbv":"GhCr", "wins":0, "losses":0, "draws":0, "id":59},
    {"name":"GolemRock",         "spin":"right", "system":"UX",  "weight":34.00, "height":0, "abbv":"GlRc", "wins":0, "losses":0, "draws":0, "id":60},
    {"name":"ShelterDrake",      "spin":"right", "system":"BX",  "weight":32.65, "height":0, "abbv":"ShDr", "wins":0, "losses":0, "draws":0, "id":61},
    {"name":"DragoonStorm",      "spin":"left",  "system":"BX",  "weight":25.35, "height":0, "abbv":"DrSt", "wins":0, "losses":0, "draws":0, "id":62},
    {"name":"StormPegasis",      "spin":"right", "system":"BX",  "weight":30.75, "height":0, "abbv":"StPg", "wins":0, "losses":0, "draws":0, "id":63},
    {"name":"VictoryValkyrie",   "spin":"right", "system":"BX",  "weight":33.05, "height":0, "abbv":"VcVl", "wins":0, "losses":0, "draws":0, "id":64},
    {"name":"XenoXcalibur",      "spin":"right", "system":"BX",  "weight":30.95, "height":0, "abbv":"XnXc", "wins":0, "losses":0, "draws":0, "id":65},
    {"name":"Brave",             "spin":"right", "system":"CX",  "weight":31.06, "height":0, "abbv":"Br",   "wins":0, "losses":0, "draws":0, "id":66},
    {"name":"Arc",               "spin":"right", "system":"CX",  "weight":29.25, "height":0, "abbv":"Ar",   "wins":0, "losses":0, "draws":0, "id":67},
    {"name":"Dark",              "spin":"right", "system":"CX",  "weight":30.50, "height":0, "abbv":"Dr",   "wins":0, "losses":0, "draws":0, "id":68},
    {"name":"Reaper",            "spin":"right", "system":"CX",  "weight":29.05, "height":0, "abbv":"Rp",   "wins":0, "losses":0, "draws":0, "id":69},
    {"name":"ScorpioSpear",      "spin":"right", "system":"UX",  "weight":39.60, "height":0, "abbv":"ScSp", "wins":0, "losses":0, "draws":0, "id":70},
    {"name":"Brush",             "spin":"right", "system":"CX",  "weight":30.30, "height":0, "abbv":"Br",   "wins":0, "losses":0, "draws":0, "id":71},
    {"name":"Hover Wyvern",      "spin":"right", "system":"UX",  "weight":35.00, "height":0, "abbv":"WyHv", "wins":0, "losses":0, "draws":0, "id":72},
    {"name":"SharkGill",         "spin":"right", "system":"BX",  "weight":29.70, "height":0, "abbv":"ShGl", "wins":0, "losses":0, "draws":0, "id":73},
    {"name":"TriceraPress",      "spin":"right", "system":"BX",  "weight":36.65, "height":0, "abbv":"TrPr", "wins":0, "losses":0, "draws":0, "id":74},
    {"name":"Blast",             "spin":"right", "system":"CX",  "weight":32.76, "height":0, "abbv":"Bl",   "wins":0, "losses":0, "draws":0, "id":75},
    {"name":"Flame",             "spin":"right", "system":"CX",  "weight":28.47, "height":0, "abbv":"Fl",   "wins":0, "losses":0, "draws":0, "id":76},
    {"name":"Volt",              "spin":"right", "system":"CX",  "weight":31.00, "height":0, "abbv":"Vl",   "wins":0, "losses":0, "draws":0, "id":77},
    {"name":"RockLeone",         "spin":"right", "system":"BX",  "weight":29.88, "height":0, "abbv":"RcLn", "wins":0, "losses":0, "draws":0, "id":78},
    {"name":"SamuraiCalibur",    "spin":"right", "system":"BX",  "weight":36.00, "height":0, "abbv":"SmCb", "wins":0, "losses":0, "draws":0, "id":79},
    {"name":"SharkScale",        "spin":"right", "system":"UX",  "weight":37.60, "height":0, "abbv":"ShSc", "wins":0, "losses":0, "draws":0, "id":80},
    {"name":"Fort",              "spin":"right", "system":"CX",  "weight":28.72, "height":0, "abbv":"Ft",   "wins":0, "losses":0, "draws":0, "id":81},
    {"name":"Wriggle",           "spin":"right", "system":"CX",  "weight":29.45, "height":0, "abbv":"Wr",   "wins":0, "losses":0, "draws":0, "id":82},
    {"name":"Antler",            "spin":"right", "system":"CX",  "weight":29.33, "height":0, "abbv":"An",   "wins":0, "losses":0, "draws":0, "id":83},
    {"name":"GoatTackle",        "spin":"right", "system":"BX",  "weight":31.46, "height":0, "abbv":"GtTc", "wins":0, "losses":0, "draws":0, "id":84},
    {"name":"Captain America",   "spin":"right", "system":"BX",  "weight":32.53, "height":0, "abbv":"CpAm", "wins":0, "losses":0, "draws":0, "id":85},
    {"name":"Red Hulk",          "spin":"right", "system":"BX",  "weight":36.18, "height":0, "abbv":"RdHl", "wins":0, "losses":0, "draws":0, "id":86},
    {"name":"Obi-Wan Kenobi",    "spin":"right", "system":"BX",  "weight":30.38, "height":0, "abbv":"ObKn", "wins":0, "losses":0, "draws":0, "id":87},
    {"name":"General Grievous",  "spin":"right", "system":"BX",  "weight":31.03, "height":0, "abbv":"GnGr", "wins":0, "losses":0, "draws":0, "id":88},
    {"name":"Bumblebee",         "spin":"right", "system":"BX",  "weight":31.85, "height":0, "abbv":"Bm",   "wins":0, "losses":0, "draws":0, "id":89},
    {"name":"Shockwave",         "spin":"right", "system":"BX",  "weight":32.26, "height":0, "abbv":"Sh",   "wins":0, "losses":0, "draws":0, "id":90},
    {"name":"Miles Morales",     "spin":"right", "system":"BX",  "weight":31.72, "height":0, "abbv":"GtTc", "wins":0, "losses":0, "draws":0, "id":91},
    {"name":"Green Goblin",      "spin":"right", "system":"BX",  "weight":31.84, "height":0, "abbv":"GtTc", "wins":0, "losses":0, "draws":0, "id":92},
    {"name":"Eclipse-U",         "spin":"right", "system":"CX",  "weight":32.25, "height":0, "abbv":"Ec:U", "wins":0, "losses":0, "draws":0, "id":93},
    {"name":"Eclipse-S",         "spin":"right", "system":"CX",  "weight":32.25, "height":0, "abbv":"Ec:S", "wins":0, "losses":0, "draws":0, "id":94},
    {"name":"ClockMirage",       "spin":"right", "system":"UX",  "weight":37.70, "height":0, "abbv":"ClMr", "wins":0, "losses":0, "draws":0, "id":95},
    {"name":"Chewbacca",         "spin":"right", "system":"BX",  "weight":31.81, "height":0, "abbv":"GtTc", "wins":0, "losses":0, "draws":0, "id":96},
    {"name":"Stormtrooper",      "spin":"right", "system":"BX",  "weight":33.12, "height":0, "abbv":"GtTc", "wins":0, "losses":0, "draws":0, "id":97},
    {"name":"Hunt",              "spin":"right", "system":"CX",  "weight":31.68, "height":0, "abbv":"Hn",   "wins":0, "losses":0, "draws":0, "id":98},
    {"name":"Might",             "spin":"right", "system":"CX",  "weight":33.27, "height":0, "abbv":"Mg",   "wins":0, "losses":0, "draws":0, "id":99},
    {"name":"Fang",              "spin":"right", "system":"CX",  "weight":30.29, "height":0, "abbv":"Fn",   "wins":0, "losses":0, "draws":0, "id":100},
    {"name":"Stun Medusa",       "spin":"right", "system":"BX",  "weight":27.32, "height":0, "abbv":"StMd", "wins":0, "losses":0, "draws":0, "id":101},
    {"name":"MeteorDragoon",     "spin":"left",  "system":"UX",  "weight":39.04, "height":0, "abbv":"MtDg", "wins":0, "losses":0, "draws":0, "id":102},
    {"name":"MummyCurse",        "spin":"right", "system":"UX",  "weight":37.32, "height":0, "abbv":"MmCr", "wins":0, "losses":0, "draws":0, "id":103},
    {"name":"Flare",             "spin":"right", "system":"CX",  "weight":31.36, "height":0, "abbv":"Fr",   "wins":0, "losses":0, "draws":0, "id":104},
    {"name":"OrochiCluster",     "spin":"right", "system":"BX",  "weight":36.36, "height":0, "abbv":"OrCl", "wins":0, "losses":0, "draws":0, "id":105},
    {"name":"Blitz",             "spin":"right", "system":"CX2", "weight":10.36, "height":0, "abbv":"Bl",   "wins":0, "losses":0, "draws":0, "id":106},
    {"name":"Fortress",          "spin":"right", "system":"CX2", "weight":10.36, "height":0, "abbv":"Fr",   "wins":0, "losses":0, "draws":0, "id":107},
    {"name":"Rage",              "spin":"right", "system":"CX2", "weight":10.36, "height":0, "abbv":"Rg",   "wins":0, "losses":0, "draws":0, "id":108},
    {"name":"DranStrike",        "spin":"right", "system":"BX2", "weight":10.36, "height":0, "abbv":"DrSt", "wins":0, "losses":0, "draws":0, "id":109},
    {"name":"BulletGriffin",     "spin":"right", "system":"UX2", "weight":10.36, "height":0, "abbv":"BlGr", "wins":0, "losses":0, "draws":0, "id":110},
    {"name":"Cutter Shinobi",    "spin":"right", "system":"UX2", "weight":10.36, "height":0, "abbv":"ShCt", "wins":0, "losses":0, "draws":0, "id":111},
    {"name":"Rampart Aegis",     "spin":"right", "system":"UX2", "weight":10.36, "height":0, "abbv":"AgRm", "wins":0, "losses":0, "draws":0, "id":112},

    
];

var assistBlades = [

    {"name":"Slash",      "spin":"right", "system":"CX", "weight":4.71, "height":0, "abbv":"S",   "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Round",      "spin":"right", "system":"CX", "weight":4.64, "height":0, "abbv":"R",   "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Bumper",     "spin":"right", "system":"CX", "weight":5.31, "height":0, "abbv":"B",   "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"Turn-A",     "spin":"right", "system":"CX", "weight":5.85, "height":0, "abbv":"T:A", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"Turn-D",     "spin":"right", "system":"CX", "weight":5.85, "height":0, "abbv":"T:D", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Charge",     "spin":"right", "system":"CX", "weight":5.05, "height":0, "abbv":"C",   "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Jaggy",      "spin":"right", "system":"CX", "weight":4.82, "height":0, "abbv":"J",   "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Assault",    "spin":"right", "system":"CX", "weight":5.00, "height":0, "abbv":"A",   "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Wheel",      "spin":"right", "system":"CX", "weight":7.26, "height":0, "abbv":"W",   "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"Massive",    "spin":"right", "system":"CX", "weight":5.32, "height":0, "abbv":"M",   "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Dual-U",     "spin":"right", "system":"CX", "weight":5.63, "height":0, "abbv":"D:U", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Dual-S",     "spin":"right", "system":"CX", "weight":5.63, "height":0, "abbv":"D:S", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Free",       "spin":"right", "system":"CX", "weight":5.82, "height":0, "abbv":"F",   "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Heavy",      "spin":"right", "system":"CX", "weight":7.94, "height":0, "abbv":"H",   "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Zillion",    "spin":"right", "system":"CX", "weight":6.66, "height":0, "abbv":"Z",   "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Knuckle",    "spin":"right", "system":"CX", "weight":6.66, "height":0, "abbv":"K",   "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Vertical",   "spin":"right", "system":"CX", "weight":0.66, "height":0, "abbv":"V",   "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Erase",      "spin":"right", "system":"CX", "weight":0.66, "height":0, "abbv":"E",   "wins":0, "losses":0, "draws":0, "id":17},
    
 ];

var rachets = [

    {"name":"3-60", "weight":6.32,  "height":6,   "abbv":"3-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"3-80", "weight":7.10,  "height":8,   "abbv":"3-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"4-60", "weight":6.30,  "height":6,   "abbv":"4-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"4-80", "weight":7.00,  "height":8,   "abbv":"4-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"5-60", "weight":6.60,  "height":6,   "abbv":"5-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"5-80", "weight":7.15,  "height":8,   "abbv":"5-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"9-60", "weight":6.19,  "height":6,   "abbv":"9-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"9-80", "weight":6.80,  "height":8,   "abbv":"9-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"1-60", "weight":6.06,  "height":6,   "abbv":"1-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"3-70", "weight":6.42,  "height":7,   "abbv":"3-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"5-70", "weight":6.70,  "height":7,   "abbv":"5-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"4-70", "weight":6.50,  "height":7,   "abbv":"4-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"1-80", "weight":6.72,  "height":8,   "abbv":"1-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"2-60", "weight":6.20,  "height":6,   "abbv":"2-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"2-80", "weight":6.90,  "height":8,   "abbv":"2-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"7-60", "weight":7.12,  "height":6,   "abbv":"7-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"9-70", "weight":6.32,  "height":7,   "abbv":"9-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"2-70", "weight":6.34,  "height":7,   "abbv":"2-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"3-85", "weight":4.79,  "height":8.5, "abbv":"3-85", "type":"simple",  "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"7-70", "weight":7.24,  "height":7,   "abbv":"7-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"0-80", "weight":7.53,  "height":8,   "abbv":"0-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"7-80", "weight":7.82,  "height":8,   "abbv":"7-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"6-60", "weight":6.13,  "height":6,   "abbv":"6-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"6-80", "weight":6.91,  "height":8,   "abbv":"6-80", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"4-55", "weight":4.78,  "height":5.5, "abbv":"4-55", "type":"simple",  "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"0-70", "weight":7.02,  "height":7,   "abbv":"0-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":25},
    {"name":"M-85", "weight":10.65, "height":8.5, "abbv":"M-85", "type":"simple",  "wins":0, "losses":0, "draws":0, "id":26},
    {"name":"6-70", "weight":6.35,  "height":7,   "abbv":"6-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":27},
    {"name":"4-50", "weight":5.92,  "height":5,   "abbv":"4-50", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":28},
    {"name":"1-70", "weight":6.16,  "height":7,   "abbv":"1-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":29},
    {"name":"9-65", "weight":4.48,  "height":6.5, "abbv":"9-65", "type":"simple",  "wins":0, "losses":0, "draws":0, "id":30},
    {"name":"0-60", "weight":6.90,  "height":6,   "abbv":"0-60", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":31},
    {"name":"7-55", "weight":5.18,  "height":5.5, "abbv":"7-55", "type":"simple",  "wins":0, "losses":0, "draws":0, "id":32},
    {"name":"1-50", "weight":0.18,  "height":5,   "abbv":"1-50", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":33},
    {"name":"8-70", "weight":0.18,  "height":7,   "abbv":"8-70", "type":"ratchet", "wins":0, "losses":0, "draws":0, "id":34},
];

var bits = [

    {"name":"Ball",         "weight":2.10,  "height":2,   "abbv":"B",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":0},
    {"name":"Flat",         "weight":2.28,  "height":2,   "abbv":"F",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":1},
    {"name":"Needle",       "weight":2.03,  "height":2,   "abbv":"N",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":2},
    {"name":"Taper",        "weight":2.19,  "height":2,   "abbv":"T",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":3},
    {"name":"High Needle",  "weight":2.17,  "height":3,   "abbv":"HN", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":4},
    {"name":"Low Flat",     "weight":2.15,  "height":1,   "abbv":"LF", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":5},
    {"name":"Point",        "weight":2.20,  "height":2,   "abbv":"P",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":6},
    {"name":"Orb",          "weight":2.02,  "height":2,   "abbv":"O",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":7},
    {"name":"Rush",         "weight":2.02,  "height":2,   "abbv":"R",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":8},
    {"name":"High Taper",   "weight":2.22,  "height":3,   "abbv":"HT", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":9},
    {"name":"Spike",        "weight":2.02,  "height":2,   "abbv":"S",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":10},
    {"name":"Gear Flat",    "weight":2.28,  "height":2,   "abbv":"GF", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":11},
    {"name":"Gear Ball",    "weight":2.08,  "height":2,   "abbv":"GB", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":12},
    {"name":"Gear Point",   "weight":2.25,  "height":2,   "abbv":"GP", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":13},
    {"name":"Gear Needle",  "weight":2.00,  "height":1.5, "abbv":"GN", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":14},
    {"name":"Accel",        "weight":2.58,  "height":2,   "abbv":"A",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":15},
    {"name":"Hexa",         "weight":2.58,  "height":1.5, "abbv":"H",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":16},
    {"name":"Disc Ball",    "weight":3.23,  "height":4,   "abbv":"DB", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":17},
    {"name":"Quake",        "weight":2.17,  "height":2.5, "abbv":"Q",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":18},
    {"name":"Metal Needle", "weight":2.75,  "height":2,   "abbv":"MN", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":19},
    {"name":"Unite",        "weight":2.12,  "height":1.5, "abbv":"U",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":20},
    {"name":"Cyclone",      "weight":2.12,  "height":2,   "abbv":"C",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":21},
    {"name":"Dot",          "weight":2.00,  "height":2,   "abbv":"D",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":22},
    {"name":"Glide",        "weight":2.52,  "height":2,   "abbv":"G",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":23},
    {"name":"Elevate",      "weight":3.23,  "height":1.5, "abbv":"E",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":24},
    {"name":"Free Ball",    "weight":1.94,  "height":2,   "abbv":"FB", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":25},
    {"name":"Trans Point",  "weight":2.21,  "height":1,   "abbv":"TP", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":26},
    {"name":"Level",        "weight":2.65,  "height":2,   "abbv":"L",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":27},
    {"name":"Bound Spike",  "weight":2.00,  "height":2,   "abbv":"BS", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":28},
    {"name":"Rubber Accel", "weight":3.10,  "height":2,   "abbv":"RA", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":29},
    {"name":"Low Rush",     "weight":1.93,  "height":1,   "abbv":"LR", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":30},
    {"name":"Under Needle", "weight":1.88,  "height":0,   "abbv":"UN", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":31},
    {"name":"Vortex",       "weight":2.15,  "height":2,   "abbv":"V",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":32},
    {"name":"Low Orb",      "weight":1.85,  "height":1,   "abbv":"LO", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":33},
    {"name":"Wedge",        "weight":1.83,  "height":2,   "abbv":"W",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":34},
    {"name":"Kick",         "weight":2.20,  "height":2,   "abbv":"K",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":35},
    {"name":"Zap",          "weight":2.49,  "height":1,   "abbv":"Z",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":36},
    {"name":"Gear Rush",    "weight":2.10,  "height":2,   "abbv":"GR", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":37},
    {"name":"Turbo",        "weight":12.59, "height":5,   "abbv":"Tr", "type":"ratchetBit", "wins":0, "losses":0, "draws":0, "id":38},
    {"name":"Wall Ball",    "weight":2.43,  "height":3,   "abbv":"WB", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":39},
    {"name":"Merge",        "weight":3.39,  "height":6,   "abbv":"M",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":40},
    {"name":"Under Flat",   "weight":2.05,  "height":0,   "abbv":"UF", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":41},
    {"name":"Trans Kick",   "weight":2.28,  "height":1.5, "abbv":"TK", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":42},
    {"name":"Operate",      "weight":14.01, "height":4,   "abbv":"Op", "type":"ratchetBit", "wins":0, "losses":0, "draws":0, "id":43},
    {"name":"Jolt",         "weight":2.54,  "height":1,   "abbv":"J",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":44},
    {"name":"Wall Wedge",   "weight":2.43,  "height":2,   "abbv":"WW", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":45},
    {"name":"Ignition",     "weight":0.43,  "height":0,   "abbv":"I",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":46},
    {"name":"Yielding",     "weight":0.43,  "height":0,   "abbv":"Y",  "type":"bit",        "wins":0, "losses":0, "draws":0, "id":47},
    {"name":"Free Flat",    "weight":0.43,  "height":0,   "abbv":"FF", "type":"bit",        "wins":0, "losses":0, "draws":0, "id":48},


];
